apiVersion: v1
kind: Service
metadata: 
  name: hello-svc
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    targetPort: 8080
    protocol: TCP
  selector: 
    app: hello-world #label selector
    #Service is looking for Pods with the label `app=hello-world`

